### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by ProbablePrime** [Robot/node-robot#2]
Ideally i need to get this working within [electron](electron.atom.io). 

There's documentation about this here: http://electron.atom.io/docs/v0.37.8/tutorial/using-native-node-modules/

And a package which takes care of most of it: https://github.com/electron/electron-rebuild for most modules. We're missing a bindings.gyp file which is what electron-rebuild requires. Instead you've got a manual build process going on. 

I'm guessing the easiest way here is to manually build electron binaries and include them in the pre-built repo. I'll look into adding stuff into the makefiles etc.

**Comment by dkrutsko** [comment]
That first link is broken. I'll also have to figure out what Electron is. But I'm absolutely interested in increasing interoperability where needed.

Yeah, there is no `bindings.gyp`. Quite frankly I really dislike the way Node/NPM handles native libraries. You have to set up so much, especially with `node-gyp` where it requires an installation of python. Plus its very hard to set up something automated for robot-js given the dependencies. I'm hoping one day the fine folks managing Node/NPM will create something better for developing native libraries.

In the meantime, yes it's a very manual process but the most used prebuilt binaries are available at: http://node.getrobot.net/. I'm hoping that's enough to get Electron working, otherwise other solutions will need to be explored.

**Comment by ProbablePrime** [comment]
[electron](http://electron.atom.io) is basically a node wrapper. it allows you to wrap a node app into packaged software.

I think i can probably get electron to load the correct precompiled for its node version and platform which might have us sorted.

**Comment by dkrutsko** [comment]
oh yes I've seen these actually, definitely interested in supporting this.

**Comment by g-sam** [comment]
Did anyone figure this out? I'm trying to use robot with the latest version of electron and getting

```
Uncaught Error: Cannot find module './darwin-x64-50'
```

After following the 'using npm' instructions in the [electron docs for native modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md). I'm using Mac Sierra.

**Comment by dkrutsko** [comment]
Hey there, so I still haven't experimented with electron however the node compile process is very well documented [here](http://getrobot.net/docs/node.html).

The way robot works is it has the JavaScript library and the pre-compiled binary for your target platform. The entire library and precompiled binary is in the `/Library` folder. When packaging your application, you need to make sure the binaries are available in that directly.

If you don't want to compile robot-js yourself, you can download the precompiled binaries from [here](http://node.getrobot.net/). NPM does this for your platform [automatically](https://github.com/Robot/robot-js/blob/master/Native/Install.js) on install.

**Comment by g-sam** [comment]
Hi, thanks for for the quick reply! The binary is there, but it is called darwin-x64-48. I'm not sure what the 48/50 refers to, but electron obviously needs 50. As far as I can see from your link there are precompiled binaries only for 16, 46, 47 and 48.

Update: here is what I have tried today: 
- downloaded electron headers from http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.3/iojs-v1.4.3-headers.tar.gz (to match electron 1.4.3)
- compiled with `make nodeVersion=iojs-1.4.3 nodeModules=50 build`. Didn't work because the folder structure for the iojs headers is different to what the makefile is expecting.
- copied all the headers from iojs-1.4.3/src and /deps into /include/node, where the makefile is expecting them.
- compiler starts but throws an error: `./Common.h:209:19: error: no member named 'GetHiddenValue' in 'v8::Object'`
- some research reveals this method was removed from the newer v8s in favour of GetPrivate.
- I tried a couple of hacky things but I know nothing of C++ or v8 and am stuck here. Help!

**Comment by dkrutsko** [comment]
The last number refers to the Node [`process.versions.modules`](https://nodejs.org/api/process.html#process_process_versions) value which represents the native addon ABI version. The ABI version number changes with each major Node release, typically as a result of native Node library changes as well as changes in V8. Below is a table matching Node versions to their respective `modules` version.

| Node Version | ABI Version |
| :-: | :-: |
| 6 | 48 |
| 5 | 47 |
| 4 | 46 |
| 0.12 | 14 |

That being said, robot-js is currently only compatible with Node 0.12, 4, 5 and 6. iojs is not supported. Although the fact that you're trying to get version 50 means that you're using Node 7? If so then you're probably going to run into compile issues (as you have). When version 7 is out of beta, I'm going to issue an update that works with it. But in the meantime you may need to downgrade to version 6.

**Comment by g-sam** [comment]
The ABI 50 is coming from the version of V8 or Node used by electron. As far as I know this is a hacked version of Node 6 -- I don't know exactly why they set the ABI to 50. There is a thread about it [here](https://github.com/electron/electron/issues/5851) which I can't really follow, but maybe someone who can will be able to think of a workaround. I was wondering whether something as simple as replacing the calls to `GetHiddenValue` with `GetPrivate` (the setters too) would do it, but that's maybe a bit optimistic.

Edit: forgot to mention, I successfully built octalmage/robotjs using an earlier version of electron which registers an abi of 48. I haven't tried this with robot-js because of the lack of a `bindings.gyp` and no support in the makefile for the headers structure used by electron, but it might work. Still, would love a way to use robot-js with the latest electron!

**Comment by dkrutsko** [comment]
So I just found [this](https://nodejs.org/en/download/releases/) nice table which lists all the official node releases with their respective V8 and modules versions. Apparently Electron is doing what io.js did and running ahead of the curve with their V8 releases. I'm not sure what Node 7 has planned but if the V8 and modules version is not kept in sync with Electron then there would be no way for robot-js to officially support both. 

At the moment I'm assuming that each major node release uses the same modules version, but if that begins to change then it would take a lot more effort to maintain robot-js. With regards to your suggestion, I'm not sure if it's that simple since I haven't looked into Electron compatibility yet but even if I used [nan](https://github.com/nodejs/nan), I don't think that would solve the problem since nan is having the same compatibility problems as robot-js.

Either way, I think you may be on your own for this one until Node 7 is released.

**Comment by karliky** [comment]
So I've been strugling with this problem too.

Here is what I found:

- In order to get working Electron with Robot-js you need a version of Electron whose `process.versions.modules` value is 48. Latest releases of Electron have a value of `50`.
- The version of Electron that matches the requirements is the `Electron 1.1.0.`. Which internally uses ` Node.js 6.1.0, Chromium 50.0.2661.102`. You can download it from here: https://electron.atom.io/releases/
- After downloading it, put a valid Electron App inside `electron\resources\app` (just an index.html, main.js and package.json)
- Install Robot-js in that folder: `npm install -s robot-js`. This will download prebuilt binaries, in my case: `\node_modules\robot-js\Library\win32-x64-48.node`
- Require robot-js inside main.js
- Execute Electron.exe
- And then you'll see this error
![electron-robot](https://cloud.githubusercontent.com/assets/881069/23565056/6a00b078-004c-11e7-8d65-c7d0cc74689e.png)

Even if you are using the same platform, architecture and `process.versions.modules`, Electron will fail to load Robot-js.

The way to fix this is by having a valid bindings.gyp. With this we could rebuild entirely robot and Electron, and so anyone will be able to create a valid Robot-js binary for Electron.

I understand you don't like gyp, I don't like it either - I prefer cmake -. But withouth this there is no way to integrate Robot-js with Electron, and this causes a big frustration because my users have to install nodejs, npm and execute npm install etc because I cannot give them a valid executable/distributable.

If you could find a solution to this that'd be awesome, however I know you are pretty bussy with the new milestone. 

Thanks in advance and keep up the great work.

Update: The same happens with NW.js
you can read here how they manage to work with native modules https://github.com/nwjs/nw.js/wiki/Using-Node-modules

**Comment by dkrutsko** [comment]
Thanks for all your hard work @karliky. I won't give up on you and will do my best to get a working solution, even if I have to get some sort of bindings file in there. When I begin integrating robot 2.1 into robot-js I'll make sure it works properly with Electron.

**Comment by TwinkerMan** [comment]
I'm really need supporting of node-gyp for Electron

**Comment by dkrutsko** [comment]
Okay, since Node ^7 is broken at the moment, I'll take a look into fixing this issue as well while I'm fixing that.

**Comment by dkrutsko** [comment]
Okay, so I briefly looked at both Electron and Node Webkit and I must say that the whole situation is a huge mess. @karliky linked a nice [post](https://github.com/nwjs/nw.js/wiki/Using-Node-modules) about getting nw.js to work with native modules, and electron is pretty much the same.

The problem is that both of these programs run their own versions of V8, independent of what Node is running (just look at [this](https://www.npmjs.com/package/electron-abi) chart). This means that native modules compiled for Node will **not** work with electron or nw.js, they'll need custom binaries for each release they make.

Now, I don't think it's feasible for us to provide pre-compiled binaries for all these releases, nor would we want to since the people using electron and nw.js are probably developers with development environments already set up. With that being said, it's probably best to have some sort of bindings file, as the guide recommends, and have it be used in the packaging process.

Unfortunately, since V8 is constantly evolving, robot-js might have issues compiling due to deprecated functionality, as we've seen with [Node 7.0.0](https://github.com/Robot/robot-js/pull/14). So either we move to something like [Nan](https://github.com/nodejs/nan) or we try and stay on top of all the updates (which I'm trying to be better at).

Another issue is that I don't want the bindings file to interfere with normal NPM installs since not everyone will have a proper environment set up. So while electron and nw.js are fine, having pre-compiled binaries for the standard version is still something I'd like to support.

Regardless, I'll continue investigating this issue. Hopefully we can find a solution that works for everyone.

**Comment by dkrutsko** [comment]
For those struggling with Electron, please take a look at [this](https://github.com/Robot/robot-js/pull/20#issuecomment-315207337) comment. Creating a `.npmrc` and following those instructions worked for me. But please keep in mind that the fix was only introduced in #35 and won't be available until robot-js 2.0.0 gets released.
