### ISSUE TITLE
Issue with robot-js on node 7.9.0 won't install

### ISSUE THREAD

**Issue by schuster19uk** [Robot/node-robot#23]
using npm instal robot-js does not install binaries and no binaries available for node 7.9.0 it seems. Runnig app.js throws cannot find module './win32-x64-51'

**Comment by dkrutsko** [comment]
Yes, #14 fixed that and it will be released with version 1.1.0. Just need to fix the Electron build and it'll be out. In the meantime, you could use Node 6 or [compile](http://getrobot.net/docs/node.html#compiling) the binaries yourself on the dev branch. I'll close this in the meantime since it's a duplicate.

**Comment by schuster19uk** [comment]
how would I compile the binaries ?

**Comment by schuster19uk** [comment]
specifically how can I find " installed development libraries and NodeModules represents the matching Node "process.versions.modules" value. "

**Comment by schuster19uk** [comment]
guessing version is 7.9.0 and modules is 51

**Comment by dkrutsko** [comment]
Yes Node 7 is version 51. You can find the information [here](https://nodejs.org/en/download/releases/).
