### ISSUE TITLE
Trying to make a bot vanilla wow

### ISSUE THREAD

**Issue by redsparton** [Robot/node-robot#3]
When I'm selecting the wow window i'm getting this error: https://gyazo.com/3a16bc955e342a79fdcb1c0b880bc74f
Heres my code:

[main.zip](https://github.com/Robot/robot-js/files/312925/main.zip)

**Comment by dkrutsko** [comment]
Hey there, unfortunately the issue section of GitHub is not a good place to find assistance with writing WoW bots. Please consider posting your question on [OwnedCore](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/). If you need to get my attention, please PM me directly since I don't always look at new posts.
