### ISSUE TITLE
Appveyor / CI not configured

### ISSUE THREAD

**Issue by DanielRuf** [Robot/node-robot#58]
It seems Appveyor is enabled but not configured (also there is no appveyor config file in the repository).

**Comment by dkrutsko** [comment]
I was testing it out but never got around to actually integrating with it.

**Comment by DanielRuf** [comment]
Let me know if you need any help with the integration and I'll prepare something.

**Comment by dkrutsko** [comment]
That would be great, I recently got everything working with `node-gyp` so the build process is simpler. But one of the reasons I haven't used a CI yet is due to the difficulty of testing this library. While the `Process` module could be made automated, UI-based modules like `Window` and `Screen` are much harder to test automatically, especially in a headless environment on multiple operating systems.

One use case for a CI, however, would be to build the binaries. It's a bit annoying that you'd have to use both AppVeyer and Travis to cover all three operating systems. Which is why I just do it manually, since it also gives me a chance to run through the test cases manually during each release.

**Comment by DanielRuf** [comment]
> UI-based modules like Window and Screen are much harder to test automatically, especially in a headless environment on multiple operating systems.

~~We can use Puppeteer for this =)~~
Sorry, misunderstood the statement.

**Comment by dkrutsko** [comment]
These modules aren't really for manipulating webpages, but rather for taking screenshots of the entire desktop, querying the number of monitors, manipulating windows on the desktop and moving data in and out of the clipboard. One way would be to have a desktop environment but simulate it automatically using another library to compare the results. Something like JUCE or SDL would work nicely for verifying. But again, not really a CI tool.

That being said, if the CI environment is simply building, then it doesn't matter. The testing can be done in a VM and automated with the method mentioned above.

**Comment by DanielRuf** [comment]
Ah ok, then we need xvfb and other alternatives?

**Comment by DanielRuf** [comment]
But I have not so much knowledge about these specific solutions.

**Comment by dkrutsko** [comment]
Yes something like that would work, not sure if there's a similar solution for Windows and OSX.
