### ISSUE TITLE
Having trouble getting robot.Window.isAxEnabled() to succeed in Mac. Any suggestions?

### ISSUE THREAD

**Issue by harshayburadkar** [Robot/node-robot#71]
I have tried adding Chrome to the Accessibility list as mentioned in docs but it didn't help. And node is showing greyed out if I try to add Node for allowing accessibility.

**Comment by p120ph37** [comment]
Use `robot.Window.isAxEnabled(true)` (the `true` part is important).  That should pop up the dialog, prompting to grant access.  Note that if you have previously denied access, the dialog may not pop up, in which case you should go to `System Preferences` -> `Security & Privacy` -> `Accessability`, unlock the window, and _delete_ (minus button) the app in question from the list so that it can pop a fresh dialog next time.

Also note that depending on how exactly you are using `robot-js`, it may not be the `Chrome` app that you need to grant access.  For example, when launching `robot-js` via `node` from the command-line, you may see the prompt mentioning your terminal window as the app requesting access.

**Comment by harshayburadkar** [comment]
Closing the issue, since it was for an old project. But thank you for the suggestion @p120ph37. This can help others running into this issue.
